# Generated by Django 3.2.5 on 2021-08-10 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210810_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_review',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 16, 21, 23, 728614)),
        ),
    ]
