# Generated by Django 3.2.5 on 2021-08-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_date_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
